cp-schema-registry:
  enabled: false

cp-kafka-rest:
  enabled: false

cp-ksql-server:
  enabled: false

cp-zookeeper:
  servers: 1

cp-kafka:
  brokers: 1
  configurationOverrides:
    "offsets.topic.replication.factor": 1
    "default.replication.factor": 1
    "min.insync.replicas": 1

cp-kafka-connect:
  configurationOverrides:
    "config.storage.replication.factor": "1"
    "offset.storage.replication.factor": "1"
    "status.storage.replication.factor": "1"
  customEnv:
    CONNECT_LOG4J_LOGGERS: "org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR"